In [1]:
import numpy as np

In [2]:
import pandas as pd

In [6]:
filename = 'data.csv'
df = pd.read_csv(filename)
print(df)

    id company_name  now_price  profit     등락률   액면가  amount_money    상장주식수  \
0    1         삼성전자      55600     800 -0.0142   100       3319199  5969783
1    2       SK하이닉스      78700       0  0.0000  5000        572938   728002
2    3        NAVER     328500   10500 -0.0310   100        539605   164263
3    4         LG화학     743000   25000 -0.0326  5000        524501    70592
4    5     삼성바이오로직스     773000    6000 -0.0077  2500        511455    66165
5    6         셀트리온     294000    5500 -0.0184  1000        396882   134994
6    7        삼성전자우      47500     400 -0.0084   100        390871   822887
7    8          현대차     172500    4000 -0.0227  5000        368578   213668
8    9          카카오     402000    8000 -0.0195   500        353816    88014
9   10        삼성SDI     439000   13500 -0.0298  5000        301876    68765
10  11       LG생활건강    1453000   30000 -0.0202  5000        226932    15618
11  12        현대모비스     230000    3500 -0.0150  5000        218626    95055
12  13         삼성물산     107500    2000 -0.0183   100        200904   186887
13  14        SK텔레콤     237500    3500 -0.0145   500        191771    80746
14  15        엔씨소프트     813000   22000 -0.0263   500        178486    21954
15  16          기아차      42150     550 -0.0129  5000        170861   405363
16  17          넷마블     197500    3000  0.0154   100        169468    85807
17  18        POSCO     186000    3000 -0.0159  5000        162168    87187
18  19         KB금융      36950     450 -0.0120  5000        153641   415808
19  20           SK     212000    4500 -0.0208   200        149164    70360
20  21       SK바이오팜     190000    8000  0.0440   500        148795    78313
21  22      SK이노베이션     154000    3000  0.0199  5000        142397    92466
22  23         신한지주      29650     350 -0.0117  5000        141548   477397
23  24           LG      80100    2900 -0.0349  5000        138218   172557
24  25         LG전자      84000    1700 -0.0198  5000        137464   163648
25  26         한국전력      20700     350 -0.0166  5000        132887   641964
26  27         삼성생명      62200    2100 -0.0327   500        124400   200000
27  28      삼성에스디에스     157000    2500 -0.0157   500        121483    77378
28  29         KT&G      82700     900 -0.0108  5000        113541   137292
29  30         삼성전기     135000    5000  0.0385  5000        100836    74694
30  31       아모레퍼시픽     169500    2500 -0.0145   500         99087    58458
31  32         삼성화재     182000    6000 -0.0319   500         86222    47375
32  33       하나금융지주      27950     100 -0.0036  5000         83918   300242
33  34        한화솔루션      48500    2800  0.0613  5000         77534   159864
34  35         신풍제약     146000   10500 -0.0671   500         77358    52985
35  36         고려아연     398000    4000 -0.0100  5000         75103    18870
36  37        한온시스템      12650      50 -0.0039   100         67526   533800
37  38        S-Oil      56900     500 -0.0087  2500         64060   112583
38  39        롯데케미칼     183000     500 -0.0027  5000         62724    34275
39  40           KT      23500     300 -0.0126  5000         61361   261112
40  41       우리금융지주       8460     130 -0.0151  5000         61104   722268
41  42       미래에셋대우       9450     270 -0.0278  5000         60982   645316
42  43       한국조선해양      86100    1500 -0.0171  5000         60936    70773
43  44         기업은행       8200      90 -0.0109  5000         60570   738664
44  45       CJ제일제당     396500    5000 -0.0125  5000         59690    15054
45  46          코웨이      79400    1600 -0.0198   500         58597    73800
46  47       포스코케미칼      89900     200  0.0022   500         54828    60988
47  48          오리온     135000    2000 -0.0146   500         53374    39536
48  49      LG디스플레이      14850       0  0.0000  5000         53136   357816
49  50    KODEX 200      31175     440 -0.0139     0         52608   168750

    외국인비율       거래량       PER     ROE  토론실
0   55.82  21982958     17.40    8.69  NaN
1   47.14   4417569     25.06    4.25  NaN
2   55.46   1168713     76.57   10.56  NaN
3   36.32    762299    128.08    1.84  NaN
4   10.20    123765    148.91    4.77  NaN
5   21.22    603813     99.16   11.19  NaN
6   87.57   2835048     14.86     NaN  NaN
7   31.82   2865128     24.86    4.32  NaN
8   32.06   1160453   -229.71   -5.81  NaN
9   41.89    425979    161.28    2.94  NaN
10  45.22     32106     33.14   20.32  NaN
11  43.68    440423     12.53    7.28  NaN
12  14.43    531470     18.78    4.77  NaN
13  35.68    483197     19.49    3.92  NaN
14  49.67    122912     34.24   14.72  NaN
15  38.87   1505135     16.05    6.50  NaN
16  22.59   2553479     81.71    3.54  NaN
17  52.18    284854     17.68    4.18  NaN
18  65.55   1617330      4.83    8.92  NaN
19  22.25    282909   -408.48    4.31  NaN
20   2.14   1249025   -172.73 -313.66  NaN
21  23.67   1592829     -6.31   -0.20  NaN
22  62.46   2268153      4.45    9.09  NaN
23  34.92    359763     17.10    5.87  NaN
24  34.32    968828     33.71    0.22  NaN
25  17.64   4101904    -14.43   -3.42  NaN
26  12.21    982136     13.83    3.26  NaN
27  12.55    152676     23.31   11.76  NaN
28  42.40    401288     11.06   12.39  NaN
29  32.42   1210153     41.55   10.18  NaN
30  31.08    234217     85.22    5.36  NaN
31  47.12    112043     13.91    4.85  NaN
32  64.35   1204355      3.31    8.77  NaN
33  19.99  23353631    -46.81   -4.02  NaN
34   6.83   3116701  4,424.24    0.80  NaN
35  24.24     48656     13.65    9.76  NaN
36  20.88   1654135     40.54   14.98  NaN
37  74.21    254454     -7.82    1.01  NaN
38  29.43    130430     34.92    5.51  NaN
39  45.28    965370     10.24    4.61  NaN
40  26.31   1634070      4.46     NaN  NaN
41  13.28   3654572     11.25    7.56  NaN
42  16.51    318866     57.90    1.40  NaN
43  11.77   1220093      3.93    7.36  NaN
44  22.45     69551      9.98    3.16  NaN
45  60.38    193016     16.69   30.74  NaN
46   7.50    539078    106.01   11.57  NaN
47  44.34     82960     20.14   14.24  NaN
48  21.41   3682602     -1.83  -22.35  NaN
49  12.79   4788126       NaN     NaN  NaN

In [11]:
# csv file ㅡ> dict로 바꾸는 법

In [12]:
import csv

In [18]:
reader = csv.DictReader(open('data.csv'))

result = {}
for row in reader:
    key = row.pop('Date')
    if key in result:
        pass
    result[key] = row
print(result)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xeb in position 36: illegal multibyte sequence